name: Jellyfin React Client Testing

on:
 push:
    branches:
      - master
 pull_request:
    branches:
      - master

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: yarn install
      env:
        CI: true
    - name: eslint
      run: yarn lint

  test:

    needs: lint

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: yarn install
      env:
        CI: true
    # FIXME: https://github.com/jellyfin/jellyfin-react-client/pull/33
    # name: yarn test
    #   run: yarn test

  release:

    needs: [lint, test]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        platform: [android, electron, ios, web, windows]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: test install, and test
      run: |
        yarn install
        # FIXME: https://github.com/jellyfin/jellyfin-react-client/pull/33
        # yarn test
      env:
        CI: true
    - name: Release ${{ matrix.platform }}
      run: yarn run ${{ matrix.platform }}:release
      env:
        CI: true
   # TODO: release-windows job
